# This is a basic workflow to help you get started with Actions

name: Trying to use github action caching when build docker image and using mounting cache in build stage 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Get Cache for Docker from Github
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-${{ github.ref_name }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref_name }}-composer-

      - name: Inject compose vendor cache in to image buildx
        uses: reproducible-containers/buildkit-cache-dance@v2
        with:
          cache-source: vendor
          cache-target: /var/www/html/vendor

      - name: Build and push Docker image with GHA cache
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: ${{ vars.DOCKER_IMAGE }}:latest
          cache-from: type=gha # Use GHA cache for restoring layers
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker image inspect ${{ vars.DOCKER_IMAGE }}:latest

      - name: Load image to the archive
        run: |
          docker save ${{ vars.DOCKER_IMAGE }} | gzip -7 > ${{ vars.DOCKER_IMAGE }}.tgz

      - name: Show some info
        run: |
          echo "Show docker images ...."
          docker images
          echo " "
          echo "directory listing ...."
          ls -l
